version: '3'
services:
  app:
    build: docker/php
    container_name: shop_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    image: nginx:1.17
    container_name: shop_nginx
    ports:
      - 1401:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/shop.local.conf:/etc/nginx/conf.d/shop.local.conf
    depends_on:
      - app
  db:
    platform: linux/x86_64
    image: mysql:8.0.25
    ports:
      - 3264:3306
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: shop_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8012:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=shop-pma.local